steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  env: ['REVISION_ID=$REVISION_ID']
  args:
  - --destination=gcr.io/$PROJECT_ID/libraries.io:$REVISION_ID
  - --cache=true
  - --cache-ttl=336h
  - --build-arg=REVISION_ID
# copy the compiled assets from the docker container to the workspace to then push to GCS
- name: 'docker'
  args: ['run', '-v', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/libraries.io:$REVISION_ID', 'cp', '-R', '/libraries.io/public/assets/', '/workspace/']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', '/workspace/assets/$REVISION_ID', 'gs://libraries-static-assets/']
