source 'https://rubygems.org'
ruby '2.4.2'

gem 'dotenv-rails', :require => 'dotenv/rails-now'
gem 'rb-readline'
gem 'oj'
gem 'rails', '5.0.6'
gem 'pg'
gem 'sassc-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'octokit'
gem 'bootstrap-sass'
gem 'will_paginate-bootstrap'
gem 'activerecord-import'
gem 'elasticsearch', '~> 2'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'nokogiri'
gem 'typhoeus'
gem 'redis'
gem 'hiredis'
gem 'rack-canonical-host'
gem 'sitemap_generator'
gem 'spdx'
gem 'sanitize-url'
gem 'semantic'
gem 'simple-rss'
gem 'faraday-http-cache'
gem 'fog-aws', '~> 1.4.0'
gem 'omniauth-github'
gem 'dalli'
gem 'counter_culture'
gem 'simple_form'
gem 'sidekiq'
gem 'sidekiq-unique-jobs'
gem 'font-awesome-rails'
gem 'mime-types', require: 'mime/types/columnar'
gem 'fast_blank'
gem 'fast_xs'
gem 'fast_xor'
gem 'premailer-rails', '1.9.7'
gem 'gemoji'
gem 'js_cookie_rails'
gem 'foreman', require: false
gem 'puma'
gem 'rack-timeout'
gem 'semantic_range'
gem 'license-compatibility'
gem 'escape_utils'
gem 'mail', require: ['mail', 'mail/utilities', 'mail/parsers']
gem 'pictogram'
gem 'rails-timeago', git: 'https://github.com/librariesio/rails-timeago'
gem 'rack-attack'
gem 'rack-attack-rate-limit', require: 'rack/attack/rate-limit'
gem 'api-pagination'
gem 'indefinite_article'
gem 'faraday_middleware'
gem 'parallel', require: nil
gem 'omniauth-gitlab'
gem 'omniauth-bitbucket'
gem 'chartkick'
gem 'groupdate'
gem 'turbolinks'
gem 'gitlab'
gem 'bitbucket_rest_api', git: 'https://github.com/librariesio/bitbucket'
gem 'github-markup', require: 'github/markup'
gem 'commonmarker'
gem 'RedCloth'
gem 'rdoc'
gem 'asciidoctor'
gem 'org-ruby'
gem 'creole'
gem 'bundler'
gem 'bibliothecary'
gem 'github-linguist'
gem 'appsignal', '~> 2.3.0'
gem 'rack-cors', :require => 'rack/cors'
gem 'active_model_serializers'
gem 'pghero'
gem 'pg_query'
gem 'schema_plus_pg_indexes'
gem 'autoprefixer-rails', '~> 7.1.2.1'
gem 'repo_miner'
gem 'amatch'
gem 'concurrent-ruby-ext'
gem 'charlock_holmes', '>= 0.7.5'

group :development do
  gem 'spring'
  gem 'sql_queries_count'
  gem 'brakeman', :require => false
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-maintenance', require: nil
  gem 'capistrano-rails-console', require: nil
  gem 'listen'
  gem 'spring-watcher-listen'
end

group :development, :test do
  gem 'rspec-rails'
end

group :test do
  gem 'factory_bot_rails'
  gem 'database_cleaner'
  gem 'rspec_junit_formatter'
  gem 'shoulda'
  gem 'simplecov', require: false
  gem 'codeclimate-test-reporter', '>= 1.0.8', require: false
  gem 'faker'
  gem 'poltergeist'
  gem 'json_spec'
  gem 'rspec-sidekiq'
end

group :production do
  gem 'bugsnag'
  gem 'lograge'
  gem 'rails_safe_tasks'
end
