# frozen_string_literal: true

source "https://rubygems.org"
ruby "2.7.8"

gem "active_model_serializers"
gem "api-pagination"
gem "asciidoctor"
gem "bibliothecary", ">= 8.6.2"
gem "bitbucket_rest_api", git: "https://github.com/librariesio/bitbucket"
gem "bootsnap", require: false
gem "bootstrap-sass"
gem "brotli"
gem "bundler"
gem "charlock_holmes", ">= 0.7.5"
gem "chronic"
gem "commonmarker"
gem "concurrent-ruby-ext"
gem "counter_culture"
gem "creole"
gem "dalli"
gem "ddtrace", "1.4.0", require: "ddtrace/auto_instrument"
gem "dotenv-rails", require: "dotenv/rails-now"
gem "elasticsearch", "~> 2"
gem "elasticsearch-model", "~> 5"
gem "elasticsearch-rails", "~> 5"
gem "escape_utils"
gem "faraday-http-cache"
gem "faraday_middleware"
gem "fast_blank"
gem "fast_xor"
gem "fast_xs"
gem "ffi"
gem "fog-aws"
gem "fog-google"
gem "font-awesome-rails", "~> 4"
gem "foreman", require: false
gem "gemoji"
gem "github-linguist"
gem "github-markup", require: "github/markup"
gem "gitlab"
gem "graphql-client", "~> 0.16.0"
gem "groupdate"
gem "hiredis"
gem "indefinite_article"
gem "jb"
gem "jquery-rails"
gem "librariesio-url-parser", "~> 1"
gem "license-compatibility"
gem "mail", require: ["mail", "mail/utilities", "mail/parsers"]
gem "marginalia"
gem "marginalia-sidekiq"
gem "mime-types", require: "mime/types/columnar"
gem "nokogiri"
gem "octicons_helper"
gem "octokit"
gem "oj"
gem "omniauth-bitbucket"
gem "omniauth-github", git: "https://github.com/omniauth/omniauth-github.git", ref: "967d769"
gem "omniauth-gitlab"
gem "org-ruby"
gem "parallel", require: nil
gem "pg"
gem "pghero"
gem "pg_query"
gem "pictogram"
gem "premailer-rails", "1.12.0"
gem "puma"
gem "rack-attack"
gem "rack-attack-rate-limit", require: "rack/attack/rate-limit"
gem "rack-canonical-host"
gem "rack-cors", require: "rack/cors"
gem "rails", "7.0.7.2"
gem "rails-timeago", git: "https://github.com/librariesio/rails-timeago"
gem "rb-readline"
gem "rdoc"
gem "redis"
gem "rubyzip", "~> 2.3.0"
gem "sanitize-url"
gem "sassc-rails"
gem "semantic", git: "https://github.com/librariesio/semantic"
gem "semantic_range"
gem "sidekiq", "< 6"
gem "sidekiq-unique-jobs", "~> 6"
gem "simple_form"
gem "simple-rss"
gem "sitemap_generator"
gem "spdx"
gem "strong_migrations", "0.8.0"
gem "tomlrb"
gem "turbolinks"
gem "typhoeus"
gem "uglifier"
gem "will_paginate-bootstrap"
gem "yajl-ruby"

group :development do
  gem "annotate"
  gem "brakeman", require: false
  gem "listen"
  gem "pry-rails"
  gem "rubocop"
  gem "sql_queries_count"
end

group :development, :test do
  gem "byebug"
  gem "pry"
  gem "pry-byebug"
  gem "rspec-rails"
end

group :test do
  gem "capybara"
  gem "database_cleaner", "~> 1.7.0"
  gem "factory_bot_rails", "~> 6.2.0"
  gem "faker"
  gem "json_spec"
  gem "rspec_junit_formatter"
  gem "rspec-sidekiq"
  gem "shoulda"
  gem "simplecov", require: false
  gem "vcr"
  gem "webmock"
end

group :production do
  gem "bugsnag"
  gem "lograge"
  gem "rails_safe_tasks"
end

gem "scenic", "~> 1.7"

gem "chartkick", "~> 3.4"
